
[language-server.rust-analyzer.config]
experimental = { testExplorer = true }

# [[language]]
# name = "rust"

# [language.debugger]
# name = "lldb-dap"
# transport = "stdio"
# command = "lldb-dap"

# [[language.debugger.templates]]
# name = "binary"
# request = "launch"
# completion = [ { name = "binary", completion = "filename" } ]
# args = { program = "{0}", initCommands = [ "command script import ~/.config/helix/scripts/lldb_rustc_primer.py" ] }

# [[language.debugger.templates]]
# name = "binary (terminal)"
# request = "launch"
# completion = [ { name = "binary", completion = "filename" } ]
# args = { program = "{0}", runInTerminal = true, waitForDebugger=true, initCommands = [ "command script import ~/.config/helix/scripts/lldb_rustc_primer.py" ] }

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
